name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Run Test
        run: |
          mkdir -p output
          go test -race  -gcflags all=-l -coverprofile=output/coverage.out ./... -coverpkg=./...
          go tool cover -html=output/coverage.out -o output/coverage.html
          go run example/main.go
          echo $?
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: # https://github.com/codecov/codecov-action
          directory: ./output
